# if we don't have the data available, then go get it
source('load_data_files_stripped.R')
library("tm")
baseDataDir <- "data/en_US/";



betterMessage('Creating Basic data summaries');

# 0 = blogs
# 1 = news
# 2 = twitter

if (TRUE) {
betterMessage(paste('Calculating lineCounts'));
lineCounts <- c(length(data_blogs_full),
               length(data_news_full),
               length(data_twitter_full));

betterMessage(paste('Calculating longestLines'));
if (!exists("numCharsB")) { numCharsB <- lapply(data_blogs_full,nchar) };
if (!exists("numCharsN")) { numCharsN <- lapply(data_news_full,nchar) };
if (!exists("numCharsT")) { numCharsT <- lapply(data_twitter_full,nchar) };


longestLines <- c(numCharsB[which.max(numCharsB)],
                  numCharsN[which.max(numCharsN)],
                  numCharsT[which.max(numCharsT)]);

#rm(list=ls(pattern='numChars'));
}

betterMessage(paste('Checking for Corpus objects'));

betterMessage(paste('Calculating wordCounts'));

# wc_file generated by command line utility:
#    wc -w en* > word_counts.txt
wc_file <- paste0(baseDataDir,'word_counts.txt')
wordcountsRaw <- read.csv(wc_file,header=FALSE,sep=' ',stringsAsFactors = FALSE)
names(wordcountsRaw) <- c('ignore','NumWords','DataFile');

wordCounts <- c(wordcountsRaw$NumWords[wordcountsRaw$DataFile==full_blogs_file],
                wordcountsRaw$NumWords[wordcountsRaw$DataFile==full_news_file],
                wordcountsRaw$NumWords[wordcountsRaw$DataFile==full_twitter_file]);


summ_table<- data.frame(c(full_blogs_file, full_news_file,full_twitter_file),lineCounts,as.array(longestLines),wordCounts)
colnames(summ_table) <- c('File','LineCounts','LongestLine','WordCounts')


betterMessage(paste('Creating Blogs Histogram'));
hist(unlist(numCharsB),main = "Blogs line length",xlab = "# characters",col = "blue",xlim = c(0,1500),breaks=10000)

betterMessage(paste('Creating News Histogram'));
hist(unlist(numCharsN),main = "Twitter line length",xlab = "# characters",col = "green",xlim = c(0,1500),breaks=1000)

betterMessage(paste('Creating Blogs Histogram'));
hist(unlist(numCharsT),main = "Twitter line length",xlab = "# characters",col = "red")

betterMessage(paste('Histograms done'));